import fetch from 'node-fetch'
let handler = async (m, { conn }) => {
  let caption =  `
╭─[𝐁𝐔𝐌𝐁𝐋𝐄𝐁𝐄𝐄 𝐁𝐎𝐓]───╮
 | 
│╭────────────────────
┴│👋 Hey comrade, ${conn.getName(m.sender)}!
⬡│🤖 I\'m 🐝𝐁𝐔𝐌𝐁𝐋𝐄𝐁𝐄𝐄 𝐁𝐎𝐓\n⬡│ I\'m up and running! 🚀
│╰────────────────────
┠───[ *BOT INFO* ]────╮
│╭────────────────────
┴│    🐝𝐁𝐔𝐌𝐁𝐋𝐄𝐁𝐄𝐄 𝐁𝐎𝐓🐝
⬡│💻 A WhatsApp bot owned by:
⬡│👨‍💻 🐝░⡷▁🅦🅐🅙🅐🅒🅚🅢▁⢾░🐝
⬡│📞 For any inquiries, contact:
⬡│📱 wa.me/254102510747
⬡│🙅‍♂️ Don't call the owner or you\'ll be
⬡│ ignored or blocked! 😬
│╰────────────────────
┠───[ *HOW TO USE* ]────⋆
┴│💡 *Some commands you can use:*
⬡│🔸 .menu \n⬡│- Shows a list of available commands
⬡│🔸 .play \n⬡│- Plays a YouTube video or audio.
⬡│🔸 .sticker \n⬡│- Converts an image to a sticker
┬│🔸 .Ai text \n⬡│- Artificial intelligence 
││ https://github.com/Wajackoya
│╰──────────────
╰────────═┅═───────
*Generated by*🐝𝐁𝐄𝐄 𝐁𝐎𝐓🐝
`.trim()
conn.sendMessage(m.chat, { image: { url: 'https://telegra.ph/file/b1ed0e3edea657d1a255b.jpg' }, caption: caption, footer: `Follow me on instagram:\n\tinstagram.com/wajackoyah_jnr` }, { quoted: m })
  //m.reply(caption)
}
handler.help = ['alive']
handler.tags = ['bot check']
handler.command = /^(alive|Hi)$/i


export default handler
